name: github pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          repository: youthradio/base-components
          token: ${{ secrets.GH_PAT_READ_WRITE }}
          path: components

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn publish-ghpages

      - name: Deploy GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          allow_empty_commit: true
          keep_files: false
          force_orphan: true

      # - name: Rebuild for Production
      #   env:
      #     BASE_URL_PRODUCTION: /
      #   run: yarn publish-ghpages
      #
      # - name: Deploy Production
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist
      #     allow_empty_commit: true
      #     keep_files: false
      #     force_orphan: true
      #     publish_branch: production
      #
      # - name: Push to Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.key }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       cd static/youngamericaspeaksup
      #       git fetch && git reset --hard FETCH_HEAD && git clean -df